# Generated by Django 2.1.7 on 2019-03-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Catégorie',
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64)),
                ('ENSP', models.SmallIntegerField(verbose_name=5)),
                ('notice', models.SmallIntegerField(verbose_name=5)),
                ('ref', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('statut', models.CharField(max_length=20)),
                ('lien', models.URLField()),
                ('rangee', models.SmallIntegerField()),
                ('colonne', models.SmallIntegerField()),
                ('etagere', models.SmallIntegerField()),
                ('date_ajout', models.DateField()),
                ('categorie', models.ForeignKey(on_delete='CASCADE', to='pages_generales.Categorie')),
            ],
            options={
                'verbose_name': 'Instrument',
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Thème',
            },
        ),
        migrations.AddField(
            model_name='instrument',
            name='theme',
            field=models.ForeignKey(on_delete='CASCADE', to='pages_generales.Theme'),
        ),
    ]
