# Generated by Django 2.1.7 on 2019-03-15 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_generales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='ENSP',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='notice',
            field=models.SmallIntegerField(),
        ),
    ]
