# Generated by Django 2.1.7 on 2019-03-15 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages_generales', '0002_auto_20190315_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colonne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Colonne',
            },
        ),
        migrations.CreateModel(
            name='Etagere',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Étagère',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.SmallIntegerField()),
                ('commentaire', models.CharField(blank=True, max_length=64, null=True)),
                ('fichier', models.FileField(null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Statut',
            },
        ),
        migrations.CreateModel(
            name='Rangee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Rangée',
            },
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Statut',
            },
        ),
        migrations.RemoveField(
            model_name='instrument',
            name='lien',
        ),
        migrations.AlterField(
            model_name='instrument',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete='SET_NULL', to='pages_generales.Categorie'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='colonne',
            field=models.ForeignKey(null=True, on_delete='SET_NULL', to='pages_generales.Colonne'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='date_ajout',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='etagere',
            field=models.ForeignKey(null=True, on_delete='SET_NULL', to='pages_generales.Etagere'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='notice',
            field=models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', to='pages_generales.Notice'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='rangee',
            field=models.ForeignKey(null=True, on_delete='SET_NULL', to='pages_generales.Rangee'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='ref',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='statut',
            field=models.ForeignKey(null=True, on_delete='SET_NULL', to='pages_generales.Statut'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='theme',
            field=models.ForeignKey(null=True, on_delete='SET_NULL', to='pages_generales.Theme'),
        ),
    ]
