# Generated by Django 2.1.7 on 2019-03-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages_generales', '0003_auto_20190315_1739'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': 'Notice'},
        ),
        migrations.AlterField(
            model_name='instrument',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete='SET_NULL', to='pages_generales.Theme'),
        ),
    ]
