# Generated by Django 2.1.7 on 2019-03-21 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages_generales', '0004_auto_20190321_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='commentaire',
            new_name='nom',
        ),
    ]
