# Generated by Django 2.1.7 on 2019-03-22 16:21

from django.db import migrations, models
import pages_generales.config


class Migration(migrations.Migration):

    dependencies = [
        ('pages_generales', '0005_auto_20190321_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pages_generales.config.renommage_image),
        ),
        migrations.AlterField(
            model_name='notice',
            name='fichier',
            field=models.FileField(null=True, upload_to=pages_generales.config.renommage_notice),
        ),
    ]
