# Generated by Django 2.1.7 on 2019-02-26 23:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='MotCle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Oral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('typeOral', models.CharField(choices=[('LC', 'Leçon de chimie'), ('LP', 'Leçon de physique'), ('M', 'Montage')], max_length=2)),
                ('discipline', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ressources.Discipline')),
            ],
        ),
        migrations.CreateModel(
            name='Ressource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de parution')),
                ('auteur', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SousCategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('cat_parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ressources.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='TypeRessource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='RessourceFichier',
            fields=[
                ('ressource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ressources.Ressource')),
                ('contenu', models.FileField(upload_to='')),
            ],
            bases=('ressources.ressource',),
        ),
        migrations.CreateModel(
            name='RessourceImage',
            fields=[
                ('ressource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ressources.Ressource')),
                ('contenu', models.ImageField(upload_to='')),
            ],
            bases=('ressources.ressource',),
        ),
        migrations.CreateModel(
            name='RessourceLien',
            fields=[
                ('ressource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ressources.Ressource')),
                ('contenu', models.URLField()),
            ],
            bases=('ressources.ressource',),
        ),
        migrations.AddField(
            model_name='ressource',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ressources.Categorie'),
        ),
        migrations.AddField(
            model_name='ressource',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ressources.Discipline'),
        ),
        migrations.AddField(
            model_name='ressource',
            name='mots_cles',
            field=models.ManyToManyField(to='ressources.MotCle'),
        ),
        migrations.AddField(
            model_name='ressource',
            name='oral',
            field=models.ManyToManyField(to='ressources.Oral'),
        ),
        migrations.AddField(
            model_name='ressource',
            name='sous_cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ressources.SousCategorie'),
        ),
        migrations.AddField(
            model_name='ressource',
            name='type_ressource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ressources.TypeRessource'),
        ),
    ]
