# Generated by Django 2.1.7 on 2019-02-27 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'verbose_name': 'Discipline'},
        ),
        migrations.AlterModelOptions(
            name='ressource',
            options={'ordering': ['date'], 'verbose_name': 'Ressource'},
        ),
        migrations.AlterField(
            model_name='categorie',
            name='nom',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='souscategorie',
            name='nom',
            field=models.CharField(max_length=30),
        ),
    ]
