# Generated by Django 2.1.7 on 2019-02-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0005_auto_20190227_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='oral',
            name='spe',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
