# Generated by Django 2.1.7 on 2019-02-27 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0006_oral_spe'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oral',
            options={'verbose_name': 'Oraux'},
        ),
        migrations.RenameField(
            model_name='oral',
            old_name='discipline',
            new_name='agreg',
        ),
    ]
