# Generated by Django 2.1.7 on 2019-02-27 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0008_auto_20190227_0927'),
    ]

    operations = [
        migrations.CreateModel(
            name='RessourceScript',
            fields=[
                ('ressource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ressources.Ressource')),
                ('contenu', models.FileField(upload_to='')),
            ],
            bases=('ressources.ressource',),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='mots_cles',
            field=models.ManyToManyField(blank=True, to='ressources.MotCle', verbose_name='mots-clés'),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='oral',
            field=models.ManyToManyField(blank=True, to='ressources.Oral'),
        ),
        migrations.AlterField(
            model_name='ressource',
            name='sous_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ressources.SousCategorie', verbose_name='sous-catégorie'),
        ),
    ]
