# Generated by Django 2.1.7 on 2019-02-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0009_auto_20190227_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oral',
            name='numero',
            field=models.PositiveSmallIntegerField(verbose_name='n°'),
        ),
    ]
