# Generated by Django 2.1.7 on 2019-03-15 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0010_auto_20190227_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorie',
            options={'verbose_name': 'Catégorie'},
        ),
        migrations.AlterModelOptions(
            name='oral',
            options={'verbose_name': 'Oral'},
        ),
        migrations.AlterModelOptions(
            name='ressourcefichier',
            options={'verbose_name': 'Ressources - Fichiers pdf'},
        ),
        migrations.AlterModelOptions(
            name='ressourceimage',
            options={'verbose_name': 'Ressources - Image'},
        ),
        migrations.AlterModelOptions(
            name='ressourcelien',
            options={'verbose_name': 'Ressources - Lien'},
        ),
        migrations.AlterModelOptions(
            name='ressourcescript',
            options={'verbose_name': 'Ressources - Script Python'},
        ),
        migrations.AddField(
            model_name='categorie',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ressources.Discipline', verbose_name='catégorie'),
        ),
        migrations.AddField(
            model_name='motcle',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ressources.Discipline', verbose_name='catégorie'),
        ),
        migrations.AlterField(
            model_name='oral',
            name='numero',
            field=models.PositiveSmallIntegerField(verbose_name='n° (ext)'),
        ),
        migrations.AlterField(
            model_name='ressourcelien',
            name='contenu',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='souscategorie',
            name='cat_parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ressources.Categorie', verbose_name='catégorie'),
        ),
    ]
