# Generated by Django 2.1.7 on 2019-03-15 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0012_auto_20190315_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='discipline',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ressources.Discipline', verbose_name='discipline'),
        ),
        migrations.AlterField(
            model_name='motcle',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ressources.Discipline', verbose_name='discipline'),
        ),
    ]
