# Generated by Django 2.1.7 on 2019-03-22 16:21

from django.db import migrations, models
import ressources.config


class Migration(migrations.Migration):

    dependencies = [
        ('ressources', '0013_auto_20190315_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ressourcefichier',
            name='contenu',
            field=models.FileField(upload_to=ressources.config.renommage),
        ),
        migrations.AlterField(
            model_name='ressourceimage',
            name='contenu',
            field=models.ImageField(upload_to=ressources.config.renommage),
        ),
        migrations.AlterField(
            model_name='ressourcescript',
            name='contenu',
            field=models.FileField(upload_to=ressources.config.renommage),
        ),
    ]
