# Generated by Django 2.1.7 on 2019-03-05 15:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions_agreg', '0003_auto_20190305_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='resultats',
            field=models.FileField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='date_inscription',
            field=models.DateField(default=datetime.datetime(2019, 3, 5, 15, 53, 52, 663848, tzinfo=utc)),
        ),
    ]
