# Generated by Django 2.1.7 on 2019-03-05 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions_agreg', '0004_auto_20190305_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('telephone', models.CharField(max_length=100)),
                ('nationalite', models.CharField(max_length=20)),
                ('date_inscription', models.DateField()),
            ],
            options={
                'verbose_name': 'Candidats',
            },
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='date_naissance',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='email',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='nationalite',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='prenom',
        ),
        migrations.RemoveField(
            model_name='inscription',
            name='telephone',
        ),
        migrations.AlterField(
            model_name='inscription',
            name='date_inscription',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='inscription',
            name='auteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inscriptions_agreg.Candidat'),
        ),
    ]
