# Generated by Django 2.1.7 on 2019-03-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions_agreg', '0005_auto_20190305_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidat',
            name='password',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
