# Generated by Django 2.1.7 on 2019-03-15 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inscriptions_agreg', '0006_candidat_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidat',
            options={'verbose_name': 'Candidat'},
        ),
        migrations.AlterModelOptions(
            name='centre',
            options={'verbose_name': 'Centre'},
        ),
        migrations.AlterModelOptions(
            name='inscription',
            options={'verbose_name': 'Inscription'},
        ),
    ]
